name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic,}
          - {ROS_DISTRO: kinetic,}
          - {ROS_DISTRO: indigo,}
    env:
      ROS_REPO: ros
      CCACHE_DIR: ${{ HOME }}/.ccache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
