# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: pre-release

on:
  workflow_dispatch:
  push:

jobs:
  default:
    strategy:
      matrix:
        distro: [noetic]

    env:
      # https://github.com/ros-industrial/industrial_ci/issues/666
      BUILDER: catkin_make_isolated
      ROS_DISTRO: ${{ matrix.distro }}
      PRERELEASE: true
      DOWNSTREAM_WORKSPACE: github:ros-planning/moveit#master
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    if: github.event_name == 'workflow_dispatch'  # only allow manual triggering
    name: "${{ matrix.distro }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache ccache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-prerelease-${{ env.ROS_DISTRO }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-prerelease-${{ env.ROS_DISTRO }}-${{ github.sha }}
            ccache-prerelease-${{ env.ROS_DISTRO }}
      - uses: ros-industrial/industrial_ci@master
